### ISSUE TITLE
Unskip functional tests skipped on 2.3.4 in scope of #18

### ISSUE THREAD

**Issue by RuslanKostiv1** [magento/catalog-storefront#121]
The following functional tests were failing on 2.3.4 and were skipped in scope of #18 . Unskip the tests and make sure they are green.
```
CE:
MC-219: Admin should be able to mass update attributes for bundle products
MC-11557: Check importing of configurable products with images present in filesystem
MC-14004: Export Simple product and Configurable products with assigned images
MC-14005: Export Simple and Configurable products with custom options
MC-14006: Export Simple Product assigned to Main Website and Configurable Product assigned to Custom Website
MC-14007: Export Simple Product with custom attribute
MC-14008: Export Bundle Product
MC-14009: Export grouped product with special price
MAGETWO-59323: [Cart Price Rule] Auto generated coupon code considers 'Uses per Coupon' and 'Uses per Customer' options
MC-75: Admin should be able to create a cart price rule for auto generated coupon codes
MC-88: admin should be able to bulk update attributes of configurable products
MC-20467: Admin should be able to mass update product attributes in store view scope using the Mysql search engine
MC-8510: Mass update simple product price
MC-56: Admin should be able to mass update product attributes in global scope
EE:
MC-11793: Export - Import of products does not reset Visual Merchandiser settings
MC-5352: Check url rewrites in catalog categories after changing url key
```

Changes where the tests were skipped:

* CE: https://github.com/magento/magento2/pull/28877/files
* EE: https://github.com/magento/partners-magento2ee/pull/287/files

Branches:
```
sources:
  ce:
    repo: https://github.com/magento/magento2.git
    branch: develop-storefront
  ee:
    repo: https://github.com/magento/partners-magento2ee.git
    branch: develop-storefront
  catalogStorefrontCe:
    repo: https://github.com/magento/catalog-storefront-ce.git
    branch: develop
  catalogStorefrontEe:
    repo: https://github.com/magento/catalog-storefront-ee.git
    branch: develop
  saasExport:
    repo: https://github.com/magento/saas-export.git
    branch: develop-storefront
  dataSolutionsServicesId:
    repo: https://github.com/magento/data-solutions-services-id.git
    branch: develop-storefront
  magentoServicesConnector:
    repo: https://github.com/magento/magento-services-connector.git
    branch: develop-storefront
```
