### ISSUE TITLE
GiftCard options - wrong sort order 

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/catalog-storefront#407]
GiftCard options sort order is wrong on MySQL 8
 - GiftCard options for specified amount should be sorted by by price ASC
   - Export API (saas-expot) may return data as is, but SF API should provide the correct sort order
 - test fixed and unskipped:
   - Magento\GiftCardProductDataExporter\Test\Integration\GiftCardProductTest::testGiftCardFixedAmountMultipleWebsites
   - \Magento\CatalogStorefront\Test\Api\Product\ProductOptions\GiftCardProductTest::testVirtualGiftCardMultiWebsite

Additionally:
* rename render_type "giftcardopenamount" to "giftcard_open*amount"
* for Specified Giftcard Amount:
  * add price to option value (productOptions.values.price field)
  * cover changes with tests (see  Magento\GiftCardProductDataExporter\Test\Integration\GiftCardProductTest::testGiftCardFixedAmountMultipleWebsites)
  * rename render_type "drop_down" to "giftcard*amount"

 
To reproduce the issue locally, please use the latest mysql:8 image from docker. Config for docker-compose (don't forget to update hostname according to your installation script):
```
  mysql8:
    image: mysql:8
    hostname: mysql8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "magento"
    shm_size: '2gb'
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
```

 

Test failed: 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/saas-export/pull/152/1a5b932428b4fc972afb99c73439fb3d/WebApi/allure-report-ee-WebAPI-GRAPHQL/index.html#categories/e18e20f5991967bcf774b5725fdac117/2d23f1e0021e737a/
 

PR: https://github.com/magento/saas-export/pull/152

used branches: 
- https://github.com/magento/catalog-storefront/tree/sf-120-open-repo
- https://github.com/mslabko/saas-export/tree/sf-120-open-repo-with-master
- CE/EE: 2.4-develop OR take branches mentioned in PR
